#ifndef MICROPY_INCLUDED_RPI_BCM283X_IT_H
#define MICROPY_INCLUDED_RPI_BCM283X_IT_H

#include "bcm283x.h"

#define IRQ_PEND_BASIC    IOREG(IO_BASE + 0xB200)
#define IRQ_PEND1         IOREG(IO_BASE + 0xB204)
#define IRQ_PEND2         IOREG(IO_BASE + 0xB208)
#define IRQ_FIQ_CONTROL   IOREG(IO_BASE + 0xB20C)
#define IRQ_ENABLE1       IOREG(IO_BASE + 0xB210)
#define IRQ_ENABLE2       IOREG(IO_BASE + 0xB214)
#define IRQ_ENABLE_BASIC  IOREG(IO_BASE + 0xB218)
#define IRQ_DISABLE1      IOREG(IO_BASE + 0xB21C)
#define IRQ_DISABLE2      IOREG(IO_BASE + 0xB220)
#define IRQ_DISABLE_BASIC IOREG(IO_BASE + 0xB224)

#define IRQ_SYSTIMER(X)  (1 << (X))

#endif // MICROPY_INCLUDED_RPI_BCM283X_IT_H
