#include <stdio.h>
#include <stdint.h>

#include "py/obj.h"
#include "py/objint.h"
#include "extmod/machine_mem.h"
#include "bcm283x_gpio.h"

STATIC const mp_rom_map_elem_t mcu_module_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_mcu) },

    { MP_ROM_QSTR(MP_QSTR_mem8), MP_ROM_PTR(&machine_mem8_obj) },
    { MP_ROM_QSTR(MP_QSTR_mem16), MP_ROM_PTR(&machine_mem16_obj) },
    { MP_ROM_QSTR(MP_QSTR_mem32), MP_ROM_PTR(&machine_mem32_obj) },

    { MP_ROM_QSTR(MP_QSTR_GPFSEL0), MP_ROM_INT(GPIO(GPFSEL0)) },
    { MP_ROM_QSTR(MP_QSTR_GPFSEL1), MP_ROM_INT(GPIO(GPFSEL1)) },
    { MP_ROM_QSTR(MP_QSTR_GPFSEL2), MP_ROM_INT(GPIO(GPFSEL2)) },
    { MP_ROM_QSTR(MP_QSTR_GPFSEL3), MP_ROM_INT(GPIO(GPFSEL3)) },
    { MP_ROM_QSTR(MP_QSTR_GPFSEL4), MP_ROM_INT(GPIO(GPFSEL4)) },
    { MP_ROM_QSTR(MP_QSTR_GPFSEL5), MP_ROM_INT(GPIO(GPFSEL5)) },
    { MP_ROM_QSTR(MP_QSTR_GPSET0), MP_ROM_INT(GPIO(GPSET0)) },
    { MP_ROM_QSTR(MP_QSTR_GPSET1), MP_ROM_INT(GPIO(GPSET1)) },
    { MP_ROM_QSTR(MP_QSTR_GPCLR0), MP_ROM_INT(GPIO(GPCLR0)) },
    { MP_ROM_QSTR(MP_QSTR_GPCLR1), MP_ROM_INT(GPIO(GPCLR1)) },
    { MP_ROM_QSTR(MP_QSTR_GPLEV0), MP_ROM_INT(GPIO(GPLEV0)) },
    { MP_ROM_QSTR(MP_QSTR_GPLEV1), MP_ROM_INT(GPIO(GPLEV1)) },
    { MP_ROM_QSTR(MP_QSTR_GPEDS0), MP_ROM_INT(GPIO(GPEDS0)) },
    { MP_ROM_QSTR(MP_QSTR_GPEDS1), MP_ROM_INT(GPIO(GPEDS1)) },
    { MP_ROM_QSTR(MP_QSTR_GPREN0), MP_ROM_INT(GPIO(GPREN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPREN1), MP_ROM_INT(GPIO(GPREN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPFEN0), MP_ROM_INT(GPIO(GPFEN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPFEN1), MP_ROM_INT(GPIO(GPFEN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPHEN0), MP_ROM_INT(GPIO(GPHEN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPHEN1), MP_ROM_INT(GPIO(GPHEN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPLEN0), MP_ROM_INT(GPIO(GPLEN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPLEN1), MP_ROM_INT(GPIO(GPLEN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPAREN0), MP_ROM_INT(GPIO(GPAREN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPAREN1), MP_ROM_INT(GPIO(GPAREN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPAFEN0), MP_ROM_INT(GPIO(GPAFEN0)) },
    { MP_ROM_QSTR(MP_QSTR_GPAFEN1), MP_ROM_INT(GPIO(GPAFEN1)) },
    { MP_ROM_QSTR(MP_QSTR_GPPUD), MP_ROM_INT(GPIO(GPPUD)) },
    { MP_ROM_QSTR(MP_QSTR_GPPUDCLK0), MP_ROM_INT(GPIO(GPPUDCLK0)) },
    { MP_ROM_QSTR(MP_QSTR_GPPUDCLK1), MP_ROM_INT(GPIO(GPPUDCLK1)) },
};

STATIC MP_DEFINE_CONST_DICT(mcu_module_globals, mcu_module_globals_table);

const mp_obj_module_t mcu_module = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*) &mcu_module_globals,
};
